[package]
license.workspace = true
name = "rangoon-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
rangoon-domain.workspace = true
rangoon-import.workspace = true
rangoon-compose.workspace = true
rangoon-compile.workspace = true
serde.workspace = true
serde_json.workspace = true
rusqlite = { version = "=0.40.2", default-features = false, features = ["bundled", "limits"] }

rangoon-workflow = { path = "../rangoon-workflow" }
