import { icon } from './icons.mjs';
import { safeText, validCapabilityContent, validCapabilityTitle } from './skills-model.mjs';

const text = safeText;
const short = value => String(value ?? '').length > 18 ? `${String(value).slice(0, 9)}…${String(value).slice(-7)}` : String(value ?? 'Unavailable');
const stamp = value => Number.isInteger(value) ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Date unavailable';
const span = value => value ? `bytes ${value.startByte}–${value.endByte} · lines ${value.startLine}–${value.endLine}` : 'Span unavailable';

export function renderSkillsView(state) {
  const current = state.selected?.revision?.id === state.selected?.latestRevisionId;
  const draft = current ? state.draft : state.selected?.revision;
  const titleOK = validCapabilityTitle(draft?.title);
  const contentOK = validCapabilityContent(draft?.content);
  const readonly = !current || state.pending || state.needsReload;
  const canSave = Boolean(state.bridgeAvailable && draft?.dirty && titleOK && contentOK && !readonly);
  const canReview = Boolean(state.bridgeAvailable && !draft?.dirty && titleOK && contentOK && !state.selected?.revision?.review && !readonly);
  const createDisabled = !state.bridgeAvailable || !state.source?.saved || !validCapabilityTitle(state.createTitle) || state.pending || state.needsReload;
  const titleBytes = new TextEncoder().encode(draft?.title ?? '').length;
  const contentBytes = new TextEncoder().encode(draft?.content ?? '').length;
  const selectedId = state.selected?.id;
  const library = state.capabilities.map(item => `<button class="skills-library__item${item.id === selectedId ? ' skills-library__item--active' : ''}" type="button" data-capability="${text(item.id)}" aria-pressed="${item.id === selectedId}" ${state.pending ? 'disabled' : ''}><strong>${text(item.title)}</strong><small>${text(short(item.sourceId))} · ${item.revisionCount} revision${item.revisionCount === 1 ? '' : 's'}</small><span class="skills-badge${item.reviewed ? ' skills-badge--reviewed' : ''}">${item.reviewed ? 'Reviewed' : 'Unreviewed'}</span></button>`).join('');
  const history = state.selected?.history ?? [];
  const source = state.source;
  const derivedCount = source ? new Set(state.capabilities.filter(item => item.sourceId === source.sourceId).map(item => item.fragmentId)).size : 0;
  const libraryContents = state.listStatus === 'unavailable' ? '<p class="analysis-note">Open this page in the Rangoon desktop app to view local capabilities.</p>'
    : state.listStatus === 'loading' ? library || '<p class="analysis-note">Loading local skills…</p>'
      : state.listStatus === 'failed' ? `${library}<p class="analysis-note">Library unavailable. Prior results may be stale. Your draft remains available.</p>`
        : library || '<p class="analysis-note">No local capabilities yet.</p>';
  return `<section class="skills-page" aria-labelledby="skills-title" aria-busy="${Boolean(state.pending)}">
    <header class="skills-hero"><p class="analysis-kicker">${icon('skill',{size:16})} LOCAL CAPABILITIES</p><h1 id="skills-title" tabindex="-1">Skills <em>workbench</em></h1><p>Create reusable skills from saved source sections. Review content while keeping the original in view.</p><p class="skills-status${state.error ? ' skills-status--error' : ''}" role="status">${text(state.message)}${state.error?.code ? ` Error code: ${text(state.error.code)}.` : ''}</p></header>
    <section class="skills-source" aria-label="Saved source section"><div><p class="analysis-kicker">SOURCE → SELECTED SAVED SECTION</p><strong>${text(source?.title ?? 'No selected source section')}</strong><small>${text(source ? `${short(source.sourceId)} · ${span(source.span)} · ${derivedCount} derived section${derivedCount === 1 ? '' : 's'}` : 'Save a source, then select a section in Import & Analyze.')}</small></div><label>Title <input id="skills-create-title" maxlength="160" value="${text(state.createTitle ?? '')}" ${source?.saved && !state.pending ? '' : 'disabled'}><small id="skills-create-count">${new TextEncoder().encode(state.createTitle ?? '').length} / 160 UTF-8 bytes. Source stays unreviewed; count does not prove preservation.</small></label><button id="skills-create" class="analysis-button analysis-button--primary" type="button" ${createDisabled ? 'disabled' : ''}>${icon('skill',{size:16})}${state.pending === 'create' ? 'Creating…' : 'Create draft'}</button></section>
    <div class="skills-workbench">
      <aside class="skills-library" aria-label="Skills library"><div class="skills-panel-head"><div><p class="analysis-kicker">LIBRARY</p><h2>Saved skills</h2></div><button id="skills-reload-list" class="analysis-button analysis-button--small" type="button" ${state.pending || !state.bridgeAvailable ? 'disabled' : ''}>Reload</button></div><p class="skills-library__note">${state.listStatus === 'unavailable' ? 'Desktop app only.' : state.listStatus === 'loading' ? 'Loading library…' : state.listStatus === 'failed' ? 'Library unavailable. Current draft remains.' : `${state.capabilities.length} / 128 capabilities`}</p><div class="skills-library__list">${libraryContents}</div></aside>
      <section class="skills-editor" aria-label="Skill editor">${state.selected ? `<div class="skills-panel-head"><div><p class="analysis-kicker">${current ? 'CURRENT REVISION' : 'HISTORICAL REVISION'}</p><h2 id="skills-editor-title" tabindex="-1">${text(state.selected.revision.title)}</h2></div><span class="skills-badge${state.selected.revision.review ? ' skills-badge--reviewed' : ''}">${state.selected.revision.review ? 'Reviewed' : 'Unreviewed'}</span></div>${!current ? '<div class="skills-historical"><span>Read-only historical revision. Current draft stays retained.</span><button id="skills-return-current" class="analysis-button analysis-button--small" type="button">Return to current</button></div>' : ''}<label class="skills-field">Title <input id="skills-title-input" maxlength="160" value="${text(draft?.title ?? '')}" ${readonly ? 'readonly' : ''}><small id="skills-title-count">${titleBytes} / 160 UTF-8 bytes${titleOK ? '' : ' · use one nonblank line'}</small></label><label class="skills-field">Content <textarea id="skills-content-input" maxlength="262144" ${readonly ? 'readonly' : ''}>${text(draft?.content ?? '')}</textarea><small id="skills-content-count">${contentBytes} / 262144 UTF-8 bytes${contentOK ? '' : ' · content cannot be blank or contain NUL'}</small></label><div class="skills-actions"><button id="skills-save" class="analysis-button analysis-button--primary" type="button" ${canSave ? '' : 'disabled'}>${state.pending === 'save' ? 'Saving…' : 'Save revision'}</button><button id="skills-review" class="analysis-button" type="button" ${canReview ? '' : 'disabled'}>${state.pending === 'review' ? 'Reviewing…' : state.selected.revision.review ? 'Locally reviewed' : 'Mark reviewed'}</button></div><details class="skills-saved"><summary>Saved revision · compare with editor</summary><pre>${text(state.selected.revision.content)}</pre></details><p id="skills-draft-status" class="skills-library__note">${current && draft?.dirty ? 'Unsaved edits. Save a revision before review.' : 'Local content review does not validate, publish or authorize execution.'}</p>${state.needsReload ? '<p class="skills-conflict" role="alert">Conflict preserved this draft. <button id="skills-reload-current" class="analysis-button analysis-button--small" type="button">Reload current</button></p>' : ''}` : '<div class="skills-empty"><p class="analysis-kicker">EDITOR</p><h2>Select a skill</h2><p>Or create one from the selected saved section.</p></div>'}</section>
      <aside class="skills-provenance" aria-label="Skill provenance">${state.selected ? `<div class="skills-panel-head"><div><p class="analysis-kicker">PROVENANCE</p><h2>Original and history</h2></div></div><dl class="skills-fields"><div><dt>Authority</dt><dd>none</dd></div><div><dt>Source</dt><dd class="analysis-mono">${text(state.selected.sourceName || short(state.selected.sourceId))}</dd></div><div><dt>Source ID</dt><dd class="analysis-mono">${text(state.selected.sourceId)}</dd></div><div><dt>Fragment</dt><dd class="analysis-mono">${text(state.selected.fragmentId)}</dd></div><div><dt>Span</dt><dd>${text(span(state.selected.span))}</dd></div></dl><details class="skills-original"><summary>Original saved section</summary><pre>${text(state.selected.originalText)}</pre></details><div class="skills-history"><h3>Revision history</h3>${history.map(item => `<button type="button" class="skills-history__item${item.id === state.viewedRevisionId ? ' skills-history__item--active' : ''}" data-revision="${text(item.id)}" aria-pressed="${item.id === state.viewedRevisionId}" ${state.pending ? 'disabled' : ''}><span>${text(item.title)}</span><small>${text(stamp(item.createdAtMs))} · ${item.review ? 'Reviewed' : 'Unreviewed'}</small></button>`).join('')}</div>` : '<p class="analysis-note">Provenance appears after opening a local capability.</p>'}</aside>
    </div>
  </section>`;
}
