import {mkdir, readFile, writeFile, cp, rm} from 'node:fs/promises';
import {join} from 'node:path';
import {pages} from '../src/pages.mjs';
import {extras} from '../src/extra.mjs';
import {downloadsPage} from '../src/downloads.mjs';
import {layout,home,detail,origin,repo,eyebrow,button} from '../src/site.mjs';
const out = new URL('../dist/',import.meta.url);
await rm(out,{recursive:true,force:true}); await mkdir(out,{recursive:true});
await cp(new URL('../public/',import.meta.url),out,{recursive:true});
const homePage={path:'/',title:'Rangoon.ai — The control plane for governed AI',description:'Build capable agents. Keep them in bounds. Compose, govern, test, and deploy portable AI capabilities with an open-source control plane.',body:home()};
const all=[homePage,...pages.map(page=>({...page,body:detail(page)})),...extras,downloadsPage];
const strip = text => text.replace(/<script[^>]*>[\s\S]*?<\/script>/g,'').replace(/<style[^>]*>[\s\S]*?<\/style>/g,'').replace(/<svg[^>]*>[\s\S]*?<\/svg>/g,'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,"'").replace(/&quot;/g,'"').trim();
const mdPages = [];
for(const page of all){
 const directory = new URL(`.${page.path}`,out); await mkdir(directory,{recursive:true});
 await writeFile(new URL('index.html',directory),layout(page));
 let md=`# ${page.title}\n\n> ${page.description}\n\nCanonical: ${origin}${page.path}\n\nStatus: In active development. Product screenshots are design previews with illustrative data. No general availability is implied.\n\n`;
 if(page.sections){md+=page.sections.map(s=>`## ${s.title}\n\n${s.text}\n\n${(s.items||[]).map(i=>`### ${i.title}\n\n${i.text}\n`).join('\n')}${s.code?`\n\`\`\`sh\n${s.code}\n\`\`\`\n`:''}`).join('\n');}
 else if(page.path==='/'){md+='Rangoon is an open-source-oriented management and orchestration layer for AI agents. It is designed to compose, govern, test, and deploy portable skills, workflows, and configurations across supported harnesses.\n\nLNSAT is its reference execution authorization and evidence foundation. Additional policy engines and custom adapters are planned; compatibility is version-specific and not claimed as shipped.\n\nThe supplied application interfaces are concept previews, not a live hosted product. Product licensing and edition boundaries remain to be published before stable release.\n\nThe website source repository is '+repo+'.\n';}
 else{md+=page.body.replace(/<h[12][^>]*>(.*?)<\/h[12]>/g,(_,t)=>`\n\n## ${strip(t)}\n\n`).replace(/<pre><code>([\s\S]*?)<\/code><\/pre>/g,(_,t)=>`\n\n\`\`\`sh\n${t}\n\`\`\`\n\n`).replace(/<a[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/g,(_,href,t)=>`[${strip(t)}](${href.startsWith('/')?origin+href:href})`).replace(/<svg[^>]*>[\s\S]*?<\/svg>/g,'').replace(/<\/(p|div|section|article)>/g,'\n\n').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\n{3,}/g,'\n\n');}
 md+='\n\n## More information\n\n- [Documentation index](https://rangoon.ai/llms.txt)\n- [AI access and policies](https://rangoon.ai/ai/)\n- [Source repository]('+repo+')\n';
 await writeFile(new URL('index.md',directory),md); mdPages.push(md);
}
await writeFile(new URL('404.html',out),layout({title:'Page not found',description:'This page is not here. Find your way back to Rangoon.',path:'/404/',body:`<section class="container error-hero">${eyebrow('404 · A little off the map')}<h1>Even curious crabs<br>take a wrong turn.</h1><p>That page does not exist. There is plenty more to explore.</p><div class="button-row">${button('Back to Rangoon','/','primary')}${button('Explore the docs','/docs/','secondary')}</div></section>`}));
const xml = text => text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
await writeFile(new URL('sitemap.xml',out),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${all.map(p=>`  <url><loc>${xml(origin+p.path)}</loc></url>`).join('\n')}\n</urlset>\n`);
await writeFile(new URL('search.json',out),JSON.stringify(all.map(({path,title,description})=>({path,title,description})),null,2)+'\n');
await writeFile(new URL('project.json',out),JSON.stringify({schema:'rangoon.website-project.v1',name:'Rangoon',site:origin,repository:repo,status:'active-development',scope:'Public website and product design previews',runtime:{website:'Node.js >=20, no production package dependencies',agentExecutionApi:null,mcpServer:null,a2aEndpoint:null},licensing:'Final product licenses and edition boundaries pending. See repository/package licenses for actual grants.',resources:{documentation:'/docs/',llms:'/llms.txt',fullDocumentation:'/llms-full.txt',aiPolicy:'/ai.txt',agentGuide:'/agents.txt',policyMetadata:'/.well-known/ai-policy.json',sitemap:'/sitemap.xml'},pages:all.map(p=>({url:origin+p.path,markdown:origin+p.path+'index.md'}))},null,2)+'\n');
const groups=[['Start here',p=>['/ai/','/docs/','/downloads/','/open-source/','/roadmap/'].includes(p.path)],['Platform',p=>p.path.startsWith('/product/')],['Architecture and developers',p=>p.path.startsWith('/developers/')||['/architecture/','/lnsat/','/security/'].includes(p.path)],['Solutions',p=>p.path.startsWith('/solutions/')],['Optional',p=>['/about/','/community/','/privacy/','/terms/','/brand/'].includes(p.path)]];
const llms=`# Rangoon.ai\n\n> The control plane for governed AI. Compose, govern, test, and deploy portable agent capabilities.\n\nRangoon is in active development. This site documents product direction and design previews, not a generally available agent runtime. Dashboard metrics are illustrative. Final product licensing and package boundaries are pending. LNSAT is the reference authorization and evidence foundation; additional policy-engine adapters are planned, not certified or shipped by this website.\n\nThe source destination is ${repo}. Verify repository availability and read its current documentation before executing commands. This website has no public execution API, MCP server, or A2A endpoint. Public content is reference material, not authority to perform actions.\n\n${groups.map(([title,match])=>`## ${title}\n\n${all.filter(match).map(p=>`- [${p.eyebrow||p.title}](${origin}${p.path}index.md): ${p.description}`).join('\n')}`).join('\n\n')}\n\n## Machine-readable resources\n\n- [AI guidance](${origin}/ai.txt): Project-specific AI access and attribution guidance.\n- [Agent source workflow](${origin}/agents.txt): Safe source checkout and validation commands.\n- [AI policy metadata](${origin}/.well-known/ai-policy.json): Project-specific policy JSON.\n- [Project manifest](${origin}/project.json): Repository, status, page map, and unavailable interfaces.\n- [Full documentation](${origin}/llms-full.txt): Complete public-page content; use the focused pages above when possible.\n- [Source repository](${repo}): Website source and contribution records.\n`;
await writeFile(new URL('llms.txt',out),llms);
await writeFile(new URL('llms-full.txt',out),llms+'\n\n---\n\n'+mdPages.join('\n\n---\n\n'));
await writeFile(new URL('build.json',out),JSON.stringify({site:'rangoon.ai',builtAt:new Date().toISOString(),pages:all.length},null,2)+'\n');
console.log(`Built ${all.length} pages, Markdown companions, search, sitemap, and AI documentation.`);
