[package]
license.workspace = true
name = "rangoon-model-assistance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
rangoon-domain.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
